8-dars/api/urls.py
from django.urls import path
from .views import PostViewSet
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from rest_framework.routers import SimpleRouter

app_name = "api"
urlpatterns = [
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
]

router = SimpleRouter()
router.register("", PostViewSet, basename="post")
urlpatterns += router.urls

8-dars/core/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/v1/", include("api.urls")),
    path("api/v1/auth/", include("rest_framework.urls")),
    path("api/v1/dj-rest-auth/", include("dj_rest_auth.urls")),
    path(
        "api/v1/dj-rest-auth/registration/", include("dj_rest_auth.registration.urls")
    ),
    path("", include("posts.urls")),
    path("api/v1/schema", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/v1/schema/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),
    path(
        "api/v1/schema/swagger/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger",
    ),
]

8-dars/posts/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
)


app_name = "posts"
urlpatterns = [
    path("", PostListView.as_view(), name="list"),
    path("create/", PostCreateView.as_view(), name="create"),
    path("<int:pk>/", PostDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", PostUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", PostDeleteView.as_view(), name="delete"),
]

8-dars/api/models.py
from django.db import models

# Create your models here.

8-dars/posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return "/" + str(self.id) + "/"

    class Meta:
        ordering = ["-id"]

8-dars/api/views.py
from django.shortcuts import render
from api.serializers import PostSerializer
from posts.models import Post
from rest_framework import generics
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from .permissions import IsAuthorOrReadOnly
from rest_framework import viewsets


# Create your views here.


class PostViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticatedOrReadOnly, IsAuthorOrReadOnly]
    queryset = Post.objects.all()
    serializer_class = PostSerializer

8-dars/posts/views.py
from django.shortcuts import render
from .models import Post
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy

# Create your views here.


class PostListView(generic.ListView):
    model = Post
    template_name = "list.html"
    context_object_name = "posts"


class PostDetailView(generic.DetailView):
    model = Post
    template_name = "detail.html"
    context_object_name = "post"


class PostCreateView(LoginRequiredMixin, generic.CreateView):
    model = Post
    template_name = "create.html"
    fields = ["title", "body"]

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("posts:detail", kwargs={"pk": self.object.pk})


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Post
    template_name = "update.html"
    context_object_name = "post"
    fields = ["title", "body"]

    def test_func(self):
        post = self.get_object()
        user = self.request.user
        if user == post.author:
            return True
        else:
            return False

    def get_success_url(self):
        return reverse_lazy("posts:detail", kwargs={"pk": self.object.pk})


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Post
    template_name = "delete.html"
    context_object_name = "post"
    success_url = "/"

    def test_func(self):
        post = self.get_object()
        user = self.request.user
        if user == post.author:
            return True
        else:
            return False

8-dars/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar shadow navbar-expand-lg navbar-light bg-light">
      <div class="container ">
        <a class="navbar-brand" href="/">BLog</a>
        <div class="navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Bosh Sahifa</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'posts:create' %}">Post yozish</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container" >{% block content %}{% endblock %}</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>


8-dars/templates/create.html
{% extends "base.html" %}

{% block title %}
    Post Yaratish
{% endblock %}
{% block content %}
    <h2 class="mt-3" >Post Yaratish</h2>

    <div class="card mt-3 ">
        <div class="card-body">
            <form method="post" >{% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-primary" >Tasdiqlash</button>
            </form>
            
      </div>
    </div>
     
{% endblock %}

8-dars/templates/delete.html
{% extends "base.html" %}

{% block title %}
    O'chirish - {{post.title}}
{% endblock %}
{% block content %}
    <h2 class="mt-3" >O'chirish - {{post.title}}</h2>

    <div class="card mt-3 ">
        <div class="card-body">
            <form method="post" >{% csrf_token %}
                <p> Siz haqiqatdan ham ushbu postni o'chirib tashlamoqchimisiz.</p>
                <button class="btn btn-danger" >O'chirish</button>
                <a class="btn btn-primary"  href="/">Ortga Qaytish</a>
            </form>
            
      </div>
    </div>
     
{% endblock %}

8-dars/templates/detail.html
{% extends "base.html" %}

{% block title %}
    {{post.title}}
{% endblock %}
{% block content %}
    <h2 class="mt-3" >{{post.title}}</h2>

    <div class="card mt-3 ">
        <div class="card-body">
            {{post.body}}
            <p> <small class="text-muted" > Posted at: {{post.created}} | Author: {{post.author}} </small> </p>
            {% if post.author == request.user %}
                <small class="text-muted" >
                    <a href="{% url "posts:update" post.id %}">Update</a> |
                    <a href="{% url "posts:delete" post.id %}">Delete</a>
                </small>
            {% endif %}
      </div>
    </div>
     
{% endblock %}

8-dars/templates/list.html
{% extends "base.html" %}

{% block title %}
    Bosh Sahifa
{% endblock %}
{% block content %}
    <h2 class="mt-3" >So'ngi maqolalar</h2>
    <div class="cards" >
        {% for post in posts %}
            <div class="card mt-3 ">
                <div class="card-body">
                    {{post.title}}...<small>  <a class="text-muted" href="{{post.get_absolute_url}}">Read More</a></small>
              </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

8-dars/templates/update.html
{% extends "base.html" %}

{% block title %}
    Tahrirlash - {{post.title}}
{% endblock %}
{% block content %}
    <h2 class="mt-3" >Tahrirlash - {{post.title}}</h2>

    <div class="card mt-3 ">
        <div class="card-body">
            <form method="post" >{% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-primary" >Tasdiqlash</button>
            </form>
            
      </div>
    </div>
     
{% endblock %}